public with sharing class SalesforceTestsFixtureCalculator {
    public static Integer add(Integer leftValue, Integer rightValue) {
        return leftValue + rightValue;
    }

    public static Integer subtract(Integer leftValue, Integer rightValue) {
        return leftValue - rightValue;
    }

    public static Integer multiply(Integer leftValue, Integer rightValue) {
        return leftValue * rightValue;
    }
}
